modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-2.1"

[[mods]]
modId="witherproofed"
version="2.4.3"
displayName="Witherproofed"
logoFile="icon.png"
authors="Sajeyson"
credits="Mojang Studios, Forge Team"
description='Adds Heavy Reinforced Blocks to make wither farms'
issueTrackerURL="https://github.com/Sajeyson/Witherproofed"
displayURL="https://www.curseforge.com/minecraft/mc-mods/witherproofed"

[[dependencies.witherproofed]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.witherproofed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"