modLoader="javafml"
loaderVersion="[37,)"
license="LGPL-2.1"
[[mods]]
modId="witherproofed"
version="2.5.2"
displayName="Witherproofed"
logoFile="icon.png"
authors="Sajeyson"
credits="Mojang Studios, Forge Team"
description='Adds Heavy Reinforced Blocks to make wither farms'
[[dependencies.witherproofed]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.witherproofed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1, )"
    ordering="NONE"
    side="BOTH"
