modLoader="javafml"
loaderVersion="[40,)"
license="LGPL-2.1"
issueTrackerURL="https://github.com/Sajeyson-Dev/Witherproofed/issues"

[[mods]]
modId="witherproofed"
version="2.6.2"
displayName="Witherproofed"
logoFile="icon.png"
authors="Sajeyson"
credits="Mojang Studios, Forge Team"
description="Adds Reinforced Blocks to make wither farms with some tools."
displayURL="https://www.curseforge.com/minecraft/mc-mods/witherproofed"

[[dependencies.witherproofed]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.witherproofed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
